###
POST http://localhost:9000/auth/signin HTTP/1.1
Content-Type: application/json

{
    "nombre":"Favio",
    "apellido":"Gobai",
    "email":"gobai.favio@gmail.com",
    "contraseña":"contraseña",
    "alias":"faviob"
}

###
GET http://localhost:9000/usuario/home HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMwYTY4YTgyNWZmNjVhZGY1NzQyZGIiLCJpYXQiOjE2NDczNjUyMjIsImV4cCI6MTY0NzM3OTYyMn0.m6uVOgGn0hvYFKknXGUw1WAUOx7Xy6vrtfVqIrz1ZHc"
}


###
GET http://localhost:9000/usuario/faviob HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMwYTZhNzgyNWZmNjVhZGY1NzQyZTQiLCJpYXQiOjE2NDczNjQ1MTQsImV4cCI6MTY0NzM3ODkxNH0.PN2LEE5iIaSQVjtwkYU_uILTWql7gudEVY2_dXUqunY"
}

###
GET http://localhost:9000/auth/login HTTP/1.1
Content-Type: application/json

{
    "identificacion":"faviob",
    "contraseña":"contraseña"
}

###
PUT http://localhost:9000/usuario/desactivar_usuario HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjMwYTY4YTgyNWZmNjVhZGY1NzQyZGIiLCJpYXQiOjE2NDczNTU3MjIsImV4cCI6MTY0NzM3MDEyMn0.qItj1y5J4ynHbSnvpcgYAmRbmaTl7TMXL14_m5MBRKU"
}

###
PUT http://localhost:9000/usuario/agregar_contacto HTTP/1.1
Content-Type: application/json

{
    "identificacion":"jorger",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjMwYTY5NTgyNWZmNjVhZGY1NzQyZGUiLCJpYXQiOjE2NDczNTU3ODUsImV4cCI6MTY0NzM3MDE4NX0.wPBlymnGDVrHGH9z3HumC0RqLWLvOngM9pFFu5p7s_M"
}

###
PUT http://localhost:9000/usuario/borrar_contacto HTTP/1.1
Content-Type: application/json

{
    "identificacion":"jorgser",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjMwYTY5NTgyNWZmNjVhZGY1NzQyZGUiLCJpYXQiOjE2NDczNTU3ODUsImV4cCI6MTY0NzM3MDE4NX0.wPBlymnGDVrHGH9z3HumC0RqLWLvOngM9pFFu5p7s_M"
}

###
PUT http://localhost:9000/usuario/cambiar_privacidad HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMwYTY5YzgyNWZmNjVhZGY1NzQyZTEiLCJpYXQiOjE2NDczNjQ2MzAsImV4cCI6MTY0NzM3OTAzMH0.Nlmik6N0lbER3Zy6TaprTX1J9EHeS7vxGeaGiv85TG0"
}

###
POST http://localhost:9000/p/crear_publicacion HTTP/1.1
Content-Type: application/json

{
    "imagen":"esdenano.jpeg",
    "descripcion":"s primero!",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMwYTZhNzgyNWZmNjVhZGY1NzQyZTQiLCJpYXQiOjE2NDczNjQ1MTQsImV4cCI6MTY0NzM3ODkxNH0.PN2LEE5iIaSQVjtwkYU_uILTWql7gudEVY2_dXUqunY"
}

###
DELETE http://localhost:9000/p/borrar_publicacion HTTP/1.1
Content-Type: application/json

{
    "pid": "6230bcd6a0f17d4c80b05889",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjMwYTZhNzgyNWZmNjVhZGY1NzQyZTQiLCJpYXQiOjE2NDczNTU2MzYsImV4cCI6MTY0NzM3MDAzNn0.4nc3rs8_PNZvDIygeOjtq_5T9suhGFCB9JX4s8u--Jo"
}

###
PUT http://localhost:9000/p/modificar_publicacion HTTP/1.1
Content-Type: application/json

{
    "pid": "6230bd052f45d83625a93002",
    "imagen": "lacambie.jpeg",
    "descripcion":"Es una descripcion modiffff",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjMwYTZhNzgyNWZmNjVhZGY1NzQyZTQiLCJpYXQiOjE2NDczNTU2MzYsImV4cCI6MTY0NzM3MDAzNn0.4nc3rs8_PNZvDIygeOjtq_5T9suhGFCB9JX4s8u--Jo"
}

###
PUT http://localhost:9000/p/change_like HTTP/1.1
Content-Type: application/json

{
    "pid": "6230bd052f45d83625a93002",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI2MjMwYTZhNzgyNWZmNjVhZGY1NzQyZTQiLCJpYXQiOjE2NDczNTU2MzYsImV4cCI6MTY0NzM3MDAzNn0.4nc3rs8_PNZvDIygeOjtq_5T9suhGFCB9JX4s8u--Jo"
}

###
GET http://localhost:9000/p/6230cdf4f6049d916cfa3da7 HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMwYTY5NTgyNWZmNjVhZGY1NzQyZGUiLCJpYXQiOjE2NDczNjUyMzUsImV4cCI6MTY0NzM3OTYzNX0.bmxRizNXGbGnyY2FNVv2NDfarAoM2aOUOtCLNCYYXVM"
}

###
POST http://localhost:9000/comentario/crear_comentario HTTP/1.1
Content-Type: application/json

{
    "pid": "6230cdf4f6049d916cfa3da7",
    "message":"Lalala",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMwYTY5YzgyNWZmNjVhZGY1NzQyZTEiLCJpYXQiOjE2NDczNjQ2MzAsImV4cCI6MTY0NzM3OTAzMH0.Nlmik6N0lbER3Zy6TaprTX1J9EHeS7vxGeaGiv85TG0"
}

###
DELETE http://localhost:9000/comentario/borrar_comentario HTTP/1.1
Content-Type: application/json

{
    "pid": "6230cdf4f6049d916cfa3da7",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMwYTY5YzgyNWZmNjVhZGY1NzQyZTEiLCJpYXQiOjE2NDczNjQ2MzAsImV4cCI6MTY0NzM3OTAzMH0.Nlmik6N0lbER3Zy6TaprTX1J9EHeS7vxGeaGiv85TG0",
    "cid": "6230cd7ed58bc90b3f1c19f8"   
}

###
PUT http://localhost:9000/comentario/change_like HTTP/1.1
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMwYTY5YzgyNWZmNjVhZGY1NzQyZTEiLCJpYXQiOjE2NDczNjQ2MzAsImV4cCI6MTY0NzM3OTAzMH0.Nlmik6N0lbER3Zy6TaprTX1J9EHeS7vxGeaGiv85TG0",
    "cid": "6230cdd754f2fbca8967d765"
}

###
PUT http://localhost:9000/comentario/modificar_comentario HTTP/1.1
Content-Type: application/json

{
    "cid": "6230dd4c808314303e2117e4",
    "message":"Lalala 2",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjMwYTY5YzgyNWZmNjVhZGY1NzQyZTEiLCJpYXQiOjE2NDczNjQ2MzAsImV4cCI6MTY0NzM3OTAzMH0.Nlmik6N0lbER3Zy6TaprTX1J9EHeS7vxGeaGiv85TG0"
}